/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GlobalRouteImport } from './routes/global'
import { Route as InactiveRouteImport } from './routes/inactive'
import { Route as NetworkNetworkIdRouteImport } from './routes/network.$networkId'
import { Route as ServerServerIdRouteImport } from './routes/server.$serverId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRoute = GlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => rootRouteImport,
} as any)
const InactiveRoute = InactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkNetworkIdRoute = NetworkNetworkIdRouteImport.update({
  id: '/network/$networkId',
  path: '/network/$networkId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServerServerIdRoute = ServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/inactive': typeof InactiveRoute
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/server/$serverId': typeof ServerServerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/inactive': typeof InactiveRoute
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/server/$serverId': typeof ServerServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/global': typeof GlobalRoute
  '/inactive': typeof InactiveRoute
  '/network/$networkId': typeof NetworkNetworkIdRoute
  '/server/$serverId': typeof ServerServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/global' | '/inactive' | '/network/$networkId' | '/server/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/global' | '/inactive' | '/network/$networkId' | '/server/$serverId'
  id:
    | '__root__'
    | '/'
    | '/global'
    | '/inactive'
    | '/network/$networkId'
    | '/server/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlobalRoute: typeof GlobalRoute
  InactiveRoute: typeof InactiveRoute
  NetworkNetworkIdRoute: typeof NetworkNetworkIdRoute
  ServerServerIdRoute: typeof ServerServerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global': {
      id: '/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof GlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inactive': {
      id: '/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof InactiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network/$networkId': {
      id: '/network/$networkId'
      path: '/network/$networkId'
      fullPath: '/network/$networkId'
      preLoaderRoute: typeof NetworkNetworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/server/$serverId': {
      id: '/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof ServerServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlobalRoute: GlobalRoute,
  InactiveRoute: InactiveRoute,
  NetworkNetworkIdRoute: NetworkNetworkIdRoute,
  ServerServerIdRoute: ServerServerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
