/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrowseRouteImport } from './routes/_browse'
import { Route as BrowseIndexRouteImport } from './routes/_browse/index'
import { Route as BrowseGlobalRouteImport } from './routes/_browse/global'
import { Route as BrowseInactiveRouteImport } from './routes/_browse/inactive'
import { Route as BrowseNetworkNetworkIdRouteImport } from './routes/_browse/network.$networkId'
import { Route as BrowseServerServerIdRouteImport } from './routes/_browse/server.$serverId'

const BrowseRoute = BrowseRouteImport.update({
  id: '/_browse',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseGlobalRoute = BrowseGlobalRouteImport.update({
  id: '/global',
  path: '/global',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseInactiveRoute = BrowseInactiveRouteImport.update({
  id: '/inactive',
  path: '/inactive',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseNetworkNetworkIdRoute = BrowseNetworkNetworkIdRouteImport.update({
  id: '/network/$networkId',
  path: '/network/$networkId',
  getParentRoute: () => BrowseRoute,
} as any)
const BrowseServerServerIdRoute = BrowseServerServerIdRouteImport.update({
  id: '/server/$serverId',
  path: '/server/$serverId',
  getParentRoute: () => BrowseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof BrowseIndexRoute
  '/global': typeof BrowseGlobalRoute
  '/inactive': typeof BrowseInactiveRoute
  '/network/$networkId': typeof BrowseNetworkNetworkIdRoute
  '/server/$serverId': typeof BrowseServerServerIdRoute
}
export interface FileRoutesByTo {
  '/global': typeof BrowseGlobalRoute
  '/inactive': typeof BrowseInactiveRoute
  '/': typeof BrowseIndexRoute
  '/network/$networkId': typeof BrowseNetworkNetworkIdRoute
  '/server/$serverId': typeof BrowseServerServerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_browse': typeof BrowseRouteWithChildren
  '/_browse/global': typeof BrowseGlobalRoute
  '/_browse/inactive': typeof BrowseInactiveRoute
  '/_browse/': typeof BrowseIndexRoute
  '/_browse/network/$networkId': typeof BrowseNetworkNetworkIdRoute
  '/_browse/server/$serverId': typeof BrowseServerServerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/global' | '/inactive' | '/network/$networkId' | '/server/$serverId'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/global' | '/inactive' | '/' | '/network/$networkId' | '/server/$serverId'
  id:
    | '__root__'
    | '/_browse'
    | '/_browse/global'
    | '/_browse/inactive'
    | '/_browse/'
    | '/_browse/network/$networkId'
    | '/_browse/server/$serverId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  BrowseRoute: typeof BrowseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_browse': {
      id: '/_browse'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_browse/': {
      id: '/_browse/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/global': {
      id: '/_browse/global'
      path: '/global'
      fullPath: '/global'
      preLoaderRoute: typeof BrowseGlobalRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/inactive': {
      id: '/_browse/inactive'
      path: '/inactive'
      fullPath: '/inactive'
      preLoaderRoute: typeof BrowseInactiveRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/network/$networkId': {
      id: '/_browse/network/$networkId'
      path: '/network/$networkId'
      fullPath: '/network/$networkId'
      preLoaderRoute: typeof BrowseNetworkNetworkIdRouteImport
      parentRoute: typeof BrowseRoute
    }
    '/_browse/server/$serverId': {
      id: '/_browse/server/$serverId'
      path: '/server/$serverId'
      fullPath: '/server/$serverId'
      preLoaderRoute: typeof BrowseServerServerIdRouteImport
      parentRoute: typeof BrowseRoute
    }
  }
}

interface BrowseRouteChildren {
  BrowseGlobalRoute: typeof BrowseGlobalRoute
  BrowseInactiveRoute: typeof BrowseInactiveRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  BrowseNetworkNetworkIdRoute: typeof BrowseNetworkNetworkIdRoute
  BrowseServerServerIdRoute: typeof BrowseServerServerIdRoute
}

const BrowseRouteChildren: BrowseRouteChildren = {
  BrowseGlobalRoute: BrowseGlobalRoute,
  BrowseInactiveRoute: BrowseInactiveRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  BrowseNetworkNetworkIdRoute: BrowseNetworkNetworkIdRoute,
  BrowseServerServerIdRoute: BrowseServerServerIdRoute,
}

const BrowseRouteWithChildren =
  BrowseRoute._addFileChildren(BrowseRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  BrowseRoute: BrowseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
